"""Compatibility entry point for the historical ``src/easytowing`` path.

The package is maintained at the repository root. Redirect submodule lookup
before importing the public API so older PYTHONPATH-based launches cannot load
the stale duplicate implementation.
"""

from pathlib import Path as _Path

__path__ = [str(_Path(__file__).resolve().parents[2] / "easytowing")]

from .geometry import Point2D, normalize_angle, tangent_heading_from_icr
from .collision import (
    CapsuleEnvelope,
    CircleEnvelope,
    CollisionItem,
    ClearancePair,
    ClearanceReport,
    PolygonEnvelope,
    analyze_clearance,
    axis_aligned_rectangle,
    clearance_between_items,
)
from .linkage import (
    PlanarLinkageBranchHint,
    PlanarLinkageSpec,
    PlanarLinkageState,
    PlanarLinkageSweepResult,
    build_reference_linkage_demo,
    driver_point_arc,
    solve_planar_linkage,
    solve_planar_linkage_sweep,
    solve_reference_linkage_demo,
)
from .optimization import (
    LinkageOptimizationProblem,
    OptimizationMetrics,
    OptimizationMode,
    OptimizationResult,
    OptimizationVariable,
    OptimizationWeights,
    OptimizedVariable,
    build_branch_hint,
    build_optimized_spec,
    build_reference_optimization_problem,
    optimize_linkage_problem,
)
from .projects import ProjectRecord, ProjectRevision, ProjectStore, serialize_project, serialize_revision
from .dxf_import import DxfImportReport, DxfImportedEntity, analyze_dxf_import, apply_dxf_role_overrides, serialize_dxf_import_report
from .reporting import (
    ExportContext,
    build_dimensioned_svg,
    build_export_bundle,
    build_export_context,
    build_export_csv,
    build_export_dxf,
    build_export_pdf,
    build_export_json,
    build_steering_curves_svg,
    build_steering_sweep_bundle,
    build_swept_path_bundle,
    build_swept_path_svg,
)
from .model import (
    ArticulationJoint,
    Axle,
    MountedAxle,
    Pose2D,
    RigidBody,
    Side,
    VehicleCombination,
    VehicleLayout,
    Wheel,
    build_reference_demo_layout,
)
from .steering import (
    IdealAxleSolution,
    IdealSteeringSolution,
    IdealWheelSolution,
    ackermann_expected_angles,
    beta_to_reference_radius_mm,
    solve_ideal_steering,
)

__all__ = [
    "Point2D",
    "Pose2D",
    "normalize_angle",
    "tangent_heading_from_icr",
    "CapsuleEnvelope",
    "CircleEnvelope",
    "CollisionItem",
    "ClearancePair",
    "ClearanceReport",
    "PolygonEnvelope",
    "analyze_clearance",
    "axis_aligned_rectangle",
    "clearance_between_items",
    "RigidBody",
    "ArticulationJoint",
    "MountedAxle",
    "VehicleCombination",
    "Axle",
    "Side",
    "VehicleLayout",
    "Wheel",
    "build_reference_demo_layout",
    "PlanarLinkageBranchHint",
    "PlanarLinkageSpec",
    "PlanarLinkageState",
    "PlanarLinkageSweepResult",
    "build_reference_linkage_demo",
    "driver_point_arc",
    "solve_planar_linkage",
    "solve_planar_linkage_sweep",
    "solve_reference_linkage_demo",
    "LinkageOptimizationProblem",
    "OptimizationMetrics",
    "OptimizationMode",
    "OptimizationResult",
    "OptimizationVariable",
    "OptimizationWeights",
    "OptimizedVariable",
    "build_branch_hint",
    "build_optimized_spec",
    "build_reference_optimization_problem",
    "optimize_linkage_problem",
    "ProjectRecord",
    "ProjectRevision",
    "ProjectStore",
    "serialize_project",
    "serialize_revision",
    "DxfImportReport",
    "DxfImportedEntity",
    "analyze_dxf_import",
    "apply_dxf_role_overrides",
    "serialize_dxf_import_report",
    "ExportContext",
    "build_export_bundle",
    "build_export_context",
    "build_export_csv",
    "build_export_dxf",
    "build_export_pdf",
    "build_export_json",
    "build_steering_curves_svg",
    "build_steering_sweep_bundle",
    "build_swept_path_bundle",
    "build_swept_path_svg",
    "build_dimensioned_svg",
    "IdealAxleSolution",
    "IdealSteeringSolution",
    "IdealWheelSolution",
    "ackermann_expected_angles",
    "beta_to_reference_radius_mm",
    "solve_ideal_steering",
]
